# Generated by Django 6.0.2 on 2026-02-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_skill_remove_profile_about_profile_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='about',
        ),
    ]
