# Generated by Django 6.0.2 on 2026-02-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_contact_alter_skillcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='skillcategory',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
